In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import os

In [6]:
DATADIR = "../examples/logs/logs/"
DATASUFIX = "%sbias_%d_%d_DiseaseStatus.tsv"
AGENTPROFILE = "%sbias_%d_%d_patterns_of_life.log"

In [10]:
fulldata = pd.read_csv(DATASUFIX%(DATADIR,2000,90), sep = "\t|,", engine='python')

In [12]:
infectiousAgents = fulldata[fulldata['diseaseStatus'] == 'Infectious']
recoveredAgents = fulldata[fulldata['diseaseStatus'] == 'Recovered']

,step,agentId,[resRegion,diseaseStatus,byAgentID,time,location,checkin,biasReportingCond]
2084,1521,589,[112,Recovered,NaN,2019-07-06T06:45:00.000,POINT (742414.4208981143 3738614.81391764),Transport,]
2094,1580,17,[27,Recovered,NaN,2019-07-06T11:40:00.000,POINT (740485.0914292916 3737195.214770876),AtHome,]
2102,1620,1340,[208,Recovered,NaN,2019-07-06T15:00:00.000,POINT (741752.9705201624 3738059.611547394),AtRecreation,]
2119,1662,1571,[258,Recovered,NaN,2019-07-06T18:30:00.000,POINT (743289.0838434563 3737846.031713581),AtRecreation,]
2135,1733,979,[162,Recovered,NaN,2019-07-07T00:25:00.000,POINT (742005.5689169351 3738694.3305572555),AtHome,]
...,...,...,...,...,...,...,...,...,...
3960,16884,1131,[174,Recovered,NaN,2019-08-28T15:00:00.000,POINT (741538.2508043958 3736506.8222593367),AtWork,]
3971,17335,1700,[268,Recovered,NaN,2019-08-30T04:35:00.000,POINT (740177.4050906452 3737580.462980077),AtHome,]
3984,18315,499,[112,Recovered,NaN,2019-09-02T14:15:00.000,POINT (743073.9820585839 3735419.5696762614),AtWork,]
4008,19412,474,[112,Recovered,NaN,2019-09-06T09:40:00.000,POINT (743971.8807140752 3738330.3074165136),AtWork,]
4016,19883,1797,[268,Recovered,NaN,2019-09-08T00:55:00.000,POINT (740113.875033443 3737615.1785124913),AtHome,]